server:
  port: 8080

spring:
  activemq:
    broker-url: tcp://127.0.0.1:32768
    #    pool:
    #      enabled: true
    #    in-memory: true
    user: admin
    password: admin
  jms:
    pub-sub-domain: false  # 表示 使用topic的模式,还是使用queue